AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pushes logs, metrics and traces from AWS to Datadog.
Parameters:
  DdApiKey:
    Type: String
    NoEcho: true
    Default: ''
    Description: The Datadog API key, which will be stored in AWS Secrets Manager
  DdSite:
    Type: String
    Default: datadoghq.com
    AllowedValues:
      - datadoghq.com
      - datadoghq.eu
    Description: Set to datadoghq.eu to send data to the Datadog EU site
  FunctionName:
    Type: String
    Default: DatadogForwarder
    Description: Customize the Datadog Forwarder Lambda function name
  MemorySize:
    Type: Number
    Default: 1024
    Description: Memory size for the Datadog Forwarder Lambda function
  Timeout:
    Type: Number
    Default: 120
    Description: Timeout for the Datadog Forwarder Lambda function
  ReservedConcurrency:
    Type: Number
    Default: 100
    Description: Reserved concurrency for the Datadog Forwarder Lambda function
  LogRetentionInDays:
    Type: Number
    Default: 90
    Description: CloudWatch log retention for logs generated by the Datadog Forwarder
      Lambda function
  DdTags:
    Type: String
    Default: ''
    Description: Add custom tags to the forwarded log events, comma-delimited
      string, no trailing comma, e.g., env:prod,stack:classic
  DdFetchLambdaTags:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    Description: If set to true, the log forwarder will fetch Lambda tags using GetResources API calls and apply them to the aws.lambda.enhanced.* metrics parsed from the REPORT log
  DdUseTcp:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    Description: If set to true, the forwarder will send logs over a SSL encrypted TCP connection, instead of the default HTTPS connection
Conditions:
  SetDdFetchLambdaTags:
    Fn::Equals:
      - Ref: DdFetchLambdaTags
      - true
Resources:
  DatadogForwarder:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Ref: FunctionName
      Description: Pushes logs, metrics and traces from AWS to Datadog.
      Handler: lambda_function.lambda_handler
      MemorySize:
        Ref: MemorySize
      Runtime: python3.8
      Timeout:
        Ref: Timeout
      Layers:
      - Fn::Sub: arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Python38:10
      - Fn::Sub: arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Trace-Forwarder-Python38:3
      Environment:
        Variables:
          DD_API_KEY_SECRET_ARN:
            Ref: DdApiKeySecret
          DD_TAGS:
            Ref: DdTags
          DD_SITE:
            Ref: DdSite
          DD_FETCH_LAMBDA_TAGS:
            Ref: DdFetchLambdaTags
          DD_USE_TCP:
            Ref: DdUseTcp
      ReservedConcurrentExecutions:
        Ref: ReservedConcurrency
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource:
            Ref: DdApiKeySecret
        - !If
          - SetDdFetchLambdaTags
          -
            Effect: Allow
            Action:
              - tag:GetResources
            Resource: '*'
          - !Ref "AWS::NoValue"
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${DatadogForwarder}
      RetentionInDays:
        Ref: LogRetentionInDays
  DdApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: DdApiKey
      Description: Datadog API Key
      SecretString:
        Ref: DdApiKey
Outputs:
  DatadogForwarderArn:
    Description: Datadog Forwarder Lambda Function ARN
    Value:
      Fn::GetAtt:
      - DatadogForwarder
      - Arn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-DatadogForwarderArn
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Required Settings
      Parameters:
        - DdApiKey
        - DdSite
    - Label:
        default: Lambda Function Settings
      Parameters:
        - FunctionName
        - MemorySize
        - Timeout
        - ReservedConcurrency
        - LogRetentionInDays
    - Label:
        default: Log Forwarding Settings
      Parameters:
        - DdTags
        - DdUseTcp
    - Label:
        default: Experimental Settings
      Parameters:
        - DdFetchLambdaTags